version: '3'
services: 
  frontend:
    image: ${COMPOSE_PROJECT_NAME}/frontend:${TAG}
    build: 
      context: ${ROOT_ABSOLUTE_PATH} # set the correct context for the COPY to work
      dockerfile: ${DOCKER_FILE_PATH}
      args:  
        - CSPROJ_PATH=${CSPROJ_PATH}
        - SLN_PATH=${SLN_PATH}
        - SOLUTION_NAME=${SOLUTION_NAME} 
        - ENTRYPOINT_SCRIPT_PATH=${ENTRYPOINT_SCRIPT_PATH}        
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}