version: '3'
services: 
  frontend:
    image: ${COMPOSE_PROJECT_NAME}/frontend:${TAG}
    build: 
      context: ${ROOT_ABSOLUTE_PATH} # set the correct context for the COPY to work
      dockerfile: ${DOCKER_FILE_PATH}
      args:  
        - CSPROJ_PATH=${CSPROJ_PATH}
        - SLN_PATH=${SLN_PATH}
        - SOLUTION_NAME=${SOLUTION_NAME} 
        - ENTRYPOINT_SCRIPT_PATH=${ENTRYPOINT_SCRIPT_PATH}
    ports:
      - "${HTTP_PORT}:8080"
      - "${HTTPS_PORT}:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTP_PORTS=${HTTP_PORT}
      - ASPNETCORE_HTTPS_PORTS=${HTTPS_PORT}
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/